name_set['blooper_set'] = [
    'Fiddlesticks',
    'Brick',
    'Gracie',
    'Fudd',
    'Stegolio',
    'Maverick',
    'Blooper',
    'Bollywag',
    'Seargent',
    'Horendous',
    'Naked',
    'Disaster',
    'Poop',
    'Shitty',
    'Magenta',
    'Horrible',
    'Traveling',
    'Bukkake',
    'Felatio',
    'Fuck',
    'Fucks',
    'Dick',
    'Stunner',
    'Sticky',
    'Lick',
    'Infinity',
    'Truffle',
    'Helper',
    'Original',
    'Consenting',
    'Lany',
    'Gili',
    'Gwenaelle',
    'Samora',
    'Sodom',
    'Gomorrah',
    'Gonorrhea',
    'Lollypop',
    'Shit',
    'Bo',
    'Haggard',
    'Hole',
    'Inky',
    'Quivering',
    'Wild',
    'Weird',
    'Wizard',
    'Dracula',
    'Derek Jeter',
    'Polyamorous',
    'Dentist',
    'Pediatrist',
    'Colonoscopy',
    'Triple',
    'Backflip',
    'Mudruckers',
    'Jimmyjohns',
    'Corealis',
    'Pore',
    'Whore',
    'Woke',
    'Slut',
    'Slutstar',
    'Forensic',
    'Shuttlecock',
    'McMagic',
    'Buckaroo',
    'Kangaroo',
    'Piss',
    'Blue Jeans',
    'Hankering',
    'Hiddenkink',
    'Demure',
    'Gecko',
    'Jessica',
    'Telephone',
    'Pitching Machine',
    'Geriatric',
    'Kitten',
    'Mitten',
    'St. Paul',
    'Minneapolis',
    'Vellodrome',
    'Palladium',
    'Sawmill',
    'Nudity',
    'Crankshaft',
    'Archipelago',
    'Buttcheeks',
    'Squirtstick',
    'Watergun',
    'Riddlefun',
    'Bambi',
    'Hardwick',
    'Hinge Twiddle',
    'Carpet Steamer',
    'Golden Retreiver',
    'Footsie Danger',
    'Linx',
    'Skribbles',
    'deBeatlebelt',
    'Fibblenub',
    'Dreadlock',
    'Swiftfoot',
    'Dunkin',
    'Breadhole',
    'Wendith',
    'Doublestack',
    'Rindscale',
    'Bishop',
    'Kibble',
    'Groegger',
    'Miles',
    'Heavywink',
    'Fordayla',
    'Cy',
    'Twiggy',
    'Saphara',
    'Caulander',
    'Meadows',
    'Rose Despair',
    'Mathilda',
    'Dorkmund',
    'Bumbles',
    'Crumbles',
    'Trumbles',
    'Plop',
    'Margarette',
    'Sigmund',
    'Saphire',
    'Simpillion',
    'Lavendula',
    'Angsty',
    'Terrorize',
    'Flappy',
    'Zippo',
    'Chortle',
    'McMansion',
    'Mortuary',
    'Umbrella',
    'Fungus',
    'Mousepad',
    'Thumbnugget',
    'Twiddle',
    'Floridaville Mistake',
    'Rat',
    'Rat Mason',
    'Bugcatcher',
    'Chorby',
    'Thousand',
    'Rook',
    'Gross Buffet',
    'Kronovi',
    'Stat Buff',
    'Upskirt',
    'Gonad',
    'Truth',
    'Ksenia',
    'Wazowski',
    'M. Ward',
    'Trogdor',
    'Electrolyte',
    'DeLorean',
    'Chump',
    'Shark Bait',
    'Wedding Planner',
    'Newlywed Couple',
    'Hurtful Insult',
    'Unkownable Steve',
    'I-95',
    'Underoo',
    'Pickle Jar',
    'Cartoon Pancake',
    'Bikini',
    'Tiny Hands',
    'Trip Advisor',
    'Dot Com',
    'Communism',
    'Shad',
    'Reysbull',
    'Squishy Muffins',
    'Beertank',
    'Download Explicit',
    'Canopy Peaks',
    'Garote',
    'Slicey Knife',
    'Librarian Glasses',
    'Knit Sweater',
    'Biopsy',
    'Jeepers',
    'Twinkle',
    'Dickwag',
    'Sweaty Napalm',
    'Soggy Ham',
    'Jamjar',
    'Festival Twilight',
    'Cloud-soar',
    'Grunkle Stan',
    'Toenail Loose',
    'Sick Burn',
    'Sparkly Water',
    'Fizzy Drought',
    'Chick Magnet',
    'Hiccup',
    'House Of Pancakes',
    'Waffle Syrup',
    'Updog Withyou',
    'Inspector',
    'Spider Eye Doctor',
    'Vogue',
    'Peak Vanity',
    'Wordle',
    'Wavedash',
    'Kwiss Now',
    'Pop Hit',
    'Nofinger Linger',
    'Pip Paddycake',
    'Bouncey Castle',
  ];

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
