name_set['rude_set'] = [
    'Bellow',
    'Albee',
    'Cordelia',
    'de Bonesby',
    'Stirfry',
    'Cheddar',
    'Count Ivan Gretsky',
    'Danny Timeshare',
    'Kreedis',
    'Smellulus',
    'Butter St. Beef',
    'Grimothee Steel',
    'Deli',
    'Torrin',
    'Brian Fuck',
    'Kebin',
    'Hot Roddy',
    'Flipcup',
    'Poopus',
    'Pepsi',
    'Affair',
    'Afterbith',
    'Agitha',
    'Alfred Dawn',
    'Amber-Ale Assembleaux',
    'Amscray',
    'Apollo Nasty',
    'Archipelago Mamamia',
    'Azazel',
    'Baco',
    'Balbor',
    'Beaky',
    'Beardrix Dawn',
    'Bearegard Montcroy',
    'Beavis Palisades',
    'Bento',
    'Bidet',
    'Big Jug',
    'Big Muff',
    'Bif Pile',
    'Bisabella',
    'Bladen Corpse',
    'Boiled Peanuts',
    'Bon Peniseñaro',
    'Boosapher Tombs',
    'Booyousuck',
    'Boss Possum',
    'Braces',
    'Breadskin',
    'Broadbones',
    'Buckley Lindsingham',
    'Buddy Badnews',
    'Bukakke Pepsi',
    'Bunny Lindsingham',
    'Buttspread Steaks',
    'Caliper Starling',
    'Canyonera',
    'Carl Death',
    'Carl Lips',
    'Carlito Masterbandit',
    'Casper Dawn',
    'Catheter Axley',
    'Chamomile Yaley',
    'Chased Tools',
    'Cherished Mathew',
    'Cirrus',
    'Combatro',
    'Computer Generated Image',
    'Conrad Montcroy',
    'Cordelia Junior',
    'Corncob Drone',
    'Crime Boy',
    'Critical',
    'Cum Dangle',
    'Dan',
    'Daniel Load',
    'Davo',
    'Delicious Starling',
    'Denoument',
    'Detritus Cole',
    'Devont',
    'Devontess',
    'Diarrhea',
    'Digital Fasting',
    'Dino Cautiondale',
    'Doctor Dilemma',
    'Dodge Duranga',
    'Dorothy Stanwick',
    'Double Daddys Got A Million',
    'Downtown Squirt',
    'Draco',
    'Dunkdunk Bodybad',
    'Ebenezer Whitehead',
    'Egg',
    'Elbows Annual',
    'Elivra Romansky',
    'Etiquette Braddick',
    'Eyeballs',
    'Fairhope',
    'Fanboat',
    'Fanta',
    'Fernando Yumbo Peters',
    'Flush',
    'Fractus',
    'Freddery Steel',
    'Fremio',
    'Frodo',
    'Gareth',
    'Geraldine',
    'Gerard Deparfood',
    'Gerry Mentlegen',
    'Getouttahere',
    'Giblet',
    'Gladhands',
    'Glendale Millenium',
    'Goatse',
    'Gossamer Ogden Stiers',
    'Grandpa',
    'Grimace',
    'Hammerhair',
    'Hans Christian Pumpandsuck',
    'Helen',
    'Helmholtz',
    'Hesky Asmar',
    'Horse',
    'Illegal Rinbecca',
    'Ingenue Damnation',
    'Isaac',
    'Jaques Avoidoir',
    'Jason Baby',
    'Jean-Luc Robespierre',
    'Jeffrey123',
    'Jerry',
    'Jessica Gunther',
    'Jessup Shortsleeve',
    'Jesus Christ',
    'Joffrey',
    'John Menthol',
    'Johnny Ketchup',
    'Joshy',
    'Judge Alamo Gold',
    'Judge Cornmatters',
    'Kelvin',
    'Kidvid',
    'Kimrin',
    'Lady Blades',
    'Laquinta Debonita',
    'Legion',
    'Leif Tonklefart',
    'Lestimony Greed',
    'lexus Infinity',
    'Little One',
    'Little Pile',
    'Mansicle',
    'Marionette',
    'Marvin',
    'Maverick',
    'Mayflower Springshower',
    'Medium Pile',
    'Merde',
    'Milker',
    'Missing Carlo',
    'Mobilia Forbidress',
    'Moira Thousand',
    'Moma',
    'Morris Ironside',
    'Mother',
    'Snoozey',
    'Soup',
    'Mungo',
    'Myrtle',
    'Nastybone Onceover',
    'Natalie Armpits',
    'Nelly Mutiny',
    'New and Improved Queen',
    'Nog Romansky',
    'Noz Hagona',
    'Old Deuterantagonist',
    'Old Glove',
    'Organa',
    'Orlando',
    'Otto de Bonesby',
    'Pall Mall',
    'Pally Padnews',
    'Pebis',
    'Peg Lungs Jepenthy',
    'Penny Downtown',
    'Pensacola Pretty',
    'Peter Dogonovoch',
    'Pewter McDirty',
    'Pigsly',
    'Pipsy Pepsi',
    'Pontius DiNox',
    'Pope Bonoducci the Infinitieth',
    'Professor Chomps',
    'Professor Outside',
    'Prog',
    'Pubic',
    'Pumice',
    'Punished Lucas',
    'Regret',
    'Trombone',
    'Basilio',
    'Waterbottle',
    'Aurora Borealis',
    'Alejandro',
    'Bomtgomery',
    'Bright Zimmerman',
    'Satisfied',
    'Axel',
    'Goldendome'
  ];

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
